  import 'package:iptv/featuers/playlists/data/models/playlist_model.dart';

final List<PlaylistModel> playlists = [
    PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
     PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
     PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
     PlaylistModel(
      id: '',
      name: '',
      customerId: '',
      url: '',
      type: '',
      isActive: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];